apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ci-cd
  labels:
    app: ci-cd
  name: ci-cd
spec:
  selector:
    matchLabels:
      app: ci-cd
  template:
    metadata:
      labels:
        app: ci-cd
    spec:
      containers:
        - image: jenkins/jenkins
          name: jenkins
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-svc
  namespace: ci-cd
spec:
  type: NodePort
  selector:
    app: ci-cd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
