apiVersion: v1
kind: Namespace
metadata:
  name: test2
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test2
  labels:
    run: prosprr-frontend
  name: prosprr-frontend
spec:
  containers:
    - image: testbbn:latest
      name: prosprr-frontend
      imagePullPolicy: Never
